### ISSUE TITLE
ERROR: No pool for csvs

### ISSUE THREAD

**Issue by andy812** [citrix/citrix-k8s-ingress-controller#219]
I tried to deploy HTTPS web application on Kubernetes with the Citrix ingress controller and Let`s Encrypt using cert-manager using this [documentation](https://developer-docs.citrix.com/projects/citrix-k8s-ingress-controller/en/latest/certificate-management/acme/)
My Ingress manifest:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    ingress.citrix.com/frontend-ip: 172.20.0.53
    ingress.citrix.com/insecure-port: "80"
    ingress.citrix.com/secure-port: "443"
    ingress.citrix.com/insecure-termination: allow
    kubernetes.io/ingress.class: citrix
    kubernetes.io/tls-acme: "true"
  name: nginx-ing
  namespace: ns-ext
spec:
  rules:
  - host: example.dev
    http:
      paths:
      - backend:
          serviceName: nginx-svc
          servicePort: 80
        path: /
  tls:
    - hosts:
      - example.dev
      secretName: example-dev
```
Then i can sussessfully access **http**://example.dev/, but not **https**://example.dev/
I use citrix-k8s-ingress-controller:1.6.1

**Logs**
```
2020-04-03 10:45:19,458  - DEBUG - [nitrointerface.py:login_logout:166] (MainThread) Handling Nitro session establishment
DEBUG:docker_netscaler:Handling Nitro session establishment
2020-04-03 10:45:19,486  - DEBUG - [NSFrontendConfig.py:check_if_frontend_ingress_exist:38] (MainThread) Processing check_if_frontend_ingress_exist for ingress k8s-nginx-ing_ns-ext_443 with uid a067876a-4c0a-4ad5-a67d-1f4604d5c3b7
DEBUG:docker_netscaler:Processing check_if_frontend_ingress_exist for ingress k8s-nginx-ing_ns-ext_443 with uid a067876a-4c0a-4ad5-a67d-1f4604d5c3b7
2020-04-03 10:45:19,487  - DEBUG - [NSFrontendConfig.py:is_frontend_ingress:84] (MainThread) Checking if ingress type is Frontend
DEBUG:docker_netscaler:Checking if ingress type is Frontend
2020-04-03 10:45:19,487  - DEBUG - [NSFrontendConfig.py:check_if_frontend_ingress_exist:45] (MainThread) Frontend ingress not found for csvs k8s-172.20.0.53_443_ssl
DEBUG:docker_netscaler:Frontend ingress not found for csvs k8s-172.20.0.53_443_ssl
2020-04-03 10:45:19,487  - INFO - [nitrointerface.py:configure_ns_cs_app:3138] (MainThread) Processing instruction to configure k8s-nginx-ing_ns-ext_443 app associated with k8s-172.20.0.53_443_ssl CS VS
INFO:docker_netscaler:Processing instruction to configure k8s-nginx-ing_ns-ext_443 app associated with k8s-172.20.0.53_443_ssl CS VS
2020-04-03 10:45:19,487  - DEBUG - [nitrointerface.py:configure_ns_cs_app:3140] (MainThread) Configuring k8s-172.20.0.53_443_ssl and associated services
DEBUG:docker_netscaler:Configuring k8s-172.20.0.53_443_ssl and associated services
2020-04-03 10:45:19,516  - DEBUG - [nitrointerface.py:_create_nsapp_cs_vserver:2281] (MainThread) Appending resourceVersion number 28664494 as comment to cs vserver k8s-nginx-ing_ns-ext_443 of uid a067876a-4c0a-4ad5-a67d-1f4604d5c3b7
DEBUG:docker_netscaler:Appending resourceVersion number 28664494 as comment to cs vserver k8s-nginx-ing_ns-ext_443 of uid a067876a-4c0a-4ad5-a67d-1f4604d5c3b7
2020-04-03 10:45:19,516  - DEBUG - [nitrointerface.py:computeHashForGivenIngressInfo:342] (MainThread) NetscalerConfigState: Hashed values for a067876a-4c0a-4ad5-a67d-1f4604d5c3b7:28664494 is BGO6NV7ZNW6INZ4QOT4BQCQ3ANLHO2WI7R44VS2RCUBPMBOWUYDQ====
DEBUG:docker_netscaler:NetscalerConfigState: Hashed values for a067876a-4c0a-4ad5-a67d-1f4604d5c3b7:28664494 is BGO6NV7ZNW6INZ4QOT4BQCQ3ANLHO2WI7R44VS2RCUBPMBOWUYDQ====
2020-04-03 10:45:19,546  - ERROR - [nitrointerface.py:_create_nsapp_cs_vserver:2308] (MainThread) Nitro Exception::create_nsapp_cs_vserver::errorcode=273,message=Resource already exists
ERROR:docker_netscaler:Nitro Exception::create_nsapp_cs_vserver::errorcode=273,message=Resource already exists
2020-04-03 10:45:19,546  - DEBUG - [NSFrontendConfig.py:is_frontend_ingress:84] (MainThread) Checking if ingress type is Frontend
DEBUG:docker_netscaler:Checking if ingress type is Frontend
2020-04-03 10:45:19,575  - ERROR - [nitrointerface.py:nsapp_handle_certkeys:1851] (MainThread) Nitro Exception::nsapp_handle_certkeys::errorcode=461,message=No such Vserver
ERROR:docker_netscaler:Nitro Exception::nsapp_handle_certkeys::errorcode=461,message=No such Vserver
2020-04-03 10:45:19,575  - DEBUG - [nitrointerface.py:create_entities_for_policy:1545] (MainThread) Processing LB App k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc configuration for CS App k8s-nginx-ing_ns-ext_443
DEBUG:docker_netscaler:Processing LB App k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc configuration for CS App k8s-nginx-ing_ns-ext_443
2020-04-03 10:45:19,575  - DEBUG - [nitrointerface.py:_create_nsapp_vserver:1001] (MainThread) Proecessing LB Vserver k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc configuration
DEBUG:docker_netscaler:Proecessing LB Vserver k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc configuration
2020-04-03 10:45:19,637  - INFO - [nitrointerface.py:_create_nsapp_vserver:1022] (MainThread) LB Vserver k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc created successfully
INFO:docker_netscaler:LB Vserver k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc created successfully
2020-04-03 10:45:19,637  - DEBUG - [nitrointerface.py:is_default_backend:1534] (MainThread) Checking for default backend: policyname:k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc and rule: HTTP.REQ.HOSTNAME.SERVER.EQ("dev1-id-api.ftm.humans-it.dev") && HTTP.REQ.URL.PATH.SET_TEXT_MODE(IGNORECASE).STARTSWITH("/")
DEBUG:docker_netscaler:Checking for default backend: policyname:k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc and rule: HTTP.REQ.HOSTNAME.SERVER.EQ("dev1-id-api.ftm.humans-it.dev") && HTTP.REQ.URL.PATH.SET_TEXT_MODE(IGNORECASE).STARTSWITH("/")
2020-04-03 10:45:19,699  - INFO - [nitrointerface.py:_create_cs_action:2513] (MainThread) cs action k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc create successful
INFO:docker_netscaler:cs action k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc create successful
2020-04-03 10:45:19,761  - INFO - [nitrointerface.py:_create_cs_policy:2707] (MainThread) cs policy k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc create successful
INFO:docker_netscaler:cs policy k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc create successful
2020-04-03 10:45:19,761  - DEBUG - [nitrointerface.py:_bind_cs_vserver_cs_policy:2783] (MainThread) Processing k8s-172.20.0.53_443_ssl CS VS bind to k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc policy
DEBUG:docker_netscaler:Processing k8s-172.20.0.53_443_ssl CS VS bind to k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc policy
2020-04-03 10:45:19,794  - INFO - [nitrointerface.py:_bind_cs_vserver_cs_policy:2794] (MainThread) CSVserver and CSPolicy binding get failed with error No such resource [name, k8s-172.20.0.53_443_ssl]
INFO:docker_netscaler:CSVserver and CSPolicy binding get failed with error No such resource [name, k8s-172.20.0.53_443_ssl]
2020-04-03 10:45:19,794  - DEBUG - [policypriority.py:__init__:525] (MainThread) Intialising PolicyPriorityHandler with vs_name:k8s-172.20.0.53_443_ssl, rule=HTTP.REQ.HOSTNAME.SERVER.EQ("dev1-id-api.ftm.humans-it.dev") && HTTP.REQ.URL.PATH.SET_TEXT_MODE(IGNORECASE).STARTSWITH("/")
DEBUG:docker_netscaler:Intialising PolicyPriorityHandler with vs_name:k8s-172.20.0.53_443_ssl, rule=HTTP.REQ.HOSTNAME.SERVER.EQ("dev1-id-api.ftm.humans-it.dev") && HTTP.REQ.URL.PATH.SET_TEXT_MODE(IGNORECASE).STARTSWITH("/")
2020-04-03 10:45:19,794  - DEBUG - [NSAppInterfacePriorityPoolManager.py:isPriorityPoolCreatedForVS:332] (MainThread) isPriorityPoolCreatedForVS: No pool configured for k8s-172.20.0.53_443_ssl VS
DEBUG:docker_netscaler:isPriorityPoolCreatedForVS: No pool configured for k8s-172.20.0.53_443_ssl VS
2020-04-03 10:45:19,794  - WARNING - [NSAppInterfacePriorityPoolManager.py:getPoolForVS:307] (MainThread) NSPriorityPoolManagerPerCSVS:  Pool for k8s-172.20.0.53_443_ssl not found. So, returing None
WARNING:docker_netscaler:NSPriorityPoolManagerPerCSVS:  Pool for k8s-172.20.0.53_443_ssl not found. So, returing None
2020-04-03 10:45:19,794  - ERROR - [nitrointerface.py:create_entities_for_policy:1668] (MainThread) Exception configuring policy k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc for the application k8s-nginx-ing_ns-ext_443: No pool for csvs k8s-172.20.0.53_443_ssl
ERROR:docker_netscaler:Exception configuring policy k8s-nginx-ing_ns-ext_443_k8s-nginx-svc_ns-ext_80_svc for the application k8s-nginx-ing_ns-ext_443: No pool for csvs k8s-172.20.0.53_443_ssl
2020-04-03 10:45:19,794  - ERROR - [nitrointerface.py:create_entities_for_policy:1669] (MainThread) Traceback:
Traceback (most recent call last):
  File "/usr/src/triton/nsappinterface/nitrointerface.py", line 1594, in create_entities_for_policy
    ns_csapp.csvs_name, policyname, policy)
  File "/usr/src/triton/nsappinterface/nitrointerface.py", line 2798, in _bind_cs_vserver_cs_policy
    pri_handler = PolicyPriorityHandler(self, csname, policy, PolicyType.CS_POLICY)
  File "/usr/src/triton/../triton/nsappinterface/policypriority.py", line 530, in __init__
    self.priority_obj = priority_class(netskaler, vs_name, policy)
  File "/usr/src/triton/../triton/nsappinterface/policypriority.py", line 425, in __init__
    self.priorityPoolManager = NSPriorityPoolManagerPerCSVS().getPoolForVS(vs_name, VServerType.CSVserverType)
  File "/usr/src/triton/../triton/nsappinterface/NSAppInterfacePriorityPoolManager.py", line 308, in getPoolForVS
    raise ValueError("No pool for csvs {}".format(csvs_name))
ValueError: No pool for csvs k8s-172.20.0.53_443_ssl
ERROR:docker_netscaler:Traceback:
Traceback (most recent call last):
  File "/usr/src/triton/nsappinterface/nitrointerface.py", line 1594, in create_entities_for_policy
    ns_csapp.csvs_name, policyname, policy)
  File "/usr/src/triton/nsappinterface/nitrointerface.py", line 2798, in _bind_cs_vserver_cs_policy
    pri_handler = PolicyPriorityHandler(self, csname, policy, PolicyType.CS_POLICY)
  File "/usr/src/triton/../triton/nsappinterface/policypriority.py", line 530, in __init__
    self.priority_obj = priority_class(netskaler, vs_name, policy)
  File "/usr/src/triton/../triton/nsappinterface/policypriority.py", line 425, in __init__
    self.priorityPoolManager = NSPriorityPoolManagerPerCSVS().getPoolForVS(vs_name, VServerType.CSVserverType)
  File "/usr/src/triton/../triton/nsappinterface/NSAppInterfacePriorityPoolManager.py", line 308, in getPoolForVS
    raise ValueError("No pool for csvs {}".format(csvs_name))
ValueError: No pool for csvs k8s-172.20.0.53_443_ssl
2020-04-03 10:45:19,825  - ERROR - [nitrointerface.py:_update_ssl_vserver_sni_option:3030] (MainThread) Nitro Exception::_update_ssl_vserver_sni_option::errorcode=461,message=No such Vserver
ERROR:docker_netscaler:Nitro Exception::_update_ssl_vserver_sni_option::errorcode=461,message=No such Vserver
2020-04-03 10:45:19,854  - ERROR - [nitrointerface.py:_update_ssl_vserver_sni_option:3048] (MainThread) Nitro Exception::_update_ssl_vserver_sni_option::errorcode=461,message=No such Vserver
ERROR:docker_netscaler:Nitro Exception::_update_ssl_vserver_sni_option::errorcode=461,message=No such Vserver
2020-04-03 10:45:19,885  - ERROR - [nitrointerface.py:_update_ssl_vserver_sni_status:1965] (MainThread) Nitro Exception::_update_ssl_vserver_sni_status::errorcode=461,message=No such Vserver
ERROR:docker_netscaler:Nitro Exception::_update_ssl_vserver_sni_status::errorcode=461,message=No such Vserver
2020-04-03 10:45:19,885  - INFO - [nitrointerface.py:configure_ns_cs_app:3176] (MainThread) Finished processing instruction to configure k8s-nginx-ing_ns-ext_443 app associated with k8s-172.20.0.53_443_ssl CS VS
INFO:docker_netscaler:Finished processing instruction to configure k8s-nginx-ing_ns-ext_443 app associated with k8s-172.20.0.53_443_ssl CS VS
2020-04-03 10:45:19,885  - DEBUG - [nitrointerface.py:login_logout:185] (MainThread) Handling Nitro session logout
```
What is `pool for csvs k8s-172.20.0.53_443_ssl` and how can i fix it?

**Comment by andy812** [comment]
Fixed

**Comment by vintury** [comment]
it seems that CS server entity seems to be already existing which is causing CIC to fail configuring on port 443.
Please change ip or port to free.
