### ISSUE TITLE
[customresourcecontroller.py:stop_crd_thread:137] (MainThread) Exception during stopping watch on CRD.('NoneType' object has no attribute 'isAlive')

### ISSUE THREAD

**Issue by andy812** [citrix/citrix-k8s-ingress-controller#274]
CIC doesn't create new balancing rules in ADC after ingress deployment. Previously created ingresses works.
We use quay.io/citrix/citrix-k8s-ingress-controller:**1.7.46**, but we've got the same problem withe the last version.
Logs:
```
2020-07-16 08:23:04,090  - DEBUG - [customresourcecontroller.py:clear_all_active_crd_threads:140] (MainThread) Cleaning all crd threads started
2020-07-16 08:23:04,090  - DEBUG - [customresourcecontroller.py:stop_crd_thread:135] (MainThread) Cleanup completed for CRD Secret
2020-07-16 08:23:04,090  - DEBUG - [customresourcecontroller.py:stop_crd_thread:135] (MainThread) Cleanup completed for CRD rewritepolicy
2020-07-16 08:23:04,091  - ERROR - [customresourcecontroller.py:stop_crd_thread:137] (MainThread) Exception during stopping watch on k8service CRD.('NoneType' object has no attribute 'isAlive')
2020-07-16 08:23:04,091  - ERROR - [customresourcecontroller.py:stop_crd_thread:137] (MainThread) Exception during stopping watch on Endpoints CRD.('NoneType' object has no attribute 'isAlive')
2020-07-16 08:23:04,092  - DEBUG - [customresourcecontroller.py:stop_crd_thread:135] (MainThread) Cleanup completed for CRD Deployment
2020-07-16 08:23:04,092  - DEBUG - [customresourcecontroller.py:clear_all_active_crd_threads:144] (MainThread) Cleaning all crd threads completed
2020-07-16 08:23:04,092  - ERROR - [nstriton.py:kubernetes:122] (MainThread) Problem talking to kubernetes. Sleepping for 15 seconds

...

2020-07-16 08:23:30,898  - DEBUG - [referencemanager.py:resolve:484] (MainThread) Notifying reverse reference nodes of CRD swagger-stable.Endpoints.swagger-pg-cluster
2020-07-16 08:23:30,898  - DEBUG - [referencemanager.py:modify_references:895] (MainThread) Modify reference for CRD swagger-stable.Endpoints.swagger-pg-cluster completed
2020-07-16 08:23:30,898  - ERROR - [kubernetes.py:configure_cpx_for_all_apps:3363] (MainThread) Problem configuring target devices: traceback =
Traceback (most recent call last):
  File "/usr/src/triton/kubernetes/kubernetes.py", line 3330, in configure_cpx_for_all_apps
    apps = self.get_all_services()
  File "/usr/src/triton/kubernetes/kubernetes.py", line 2229, in get_all_services
    a = self.get_service(app)
  File "/usr/src/triton/kubernetes/kubernetes.py", line 2162, in get_service
    hostIP = self.get_node_ip_for_pod_ip(addr['targetRef']['name'],
KeyError: 'targetRef'
2020-07-16 08:23:30,899  - INFO - [kubernetes.py:configure_cpx_for_all_apps:3364] (MainThread) Setting flag for kube module reset[reinit_kubernetes]
2020-07-16 08:23:30,902  - DEBUG - [customresourcecontroller.py:sync_existing_events_from_k8s:306] (MainThread) START: Executing processing of existing CRDs for syncpolicy=SYNC-LAST
2020-07-16 08:23:30,904  - DEBUG - [customresourcecontroller.py:sync_existing_events_from_k8s:320] (MainThread) Start: Processing events for existing rewritepolicy crd
2020-07-16 08:23:30,909  - DEBUG - [exclusivestatemachine.py:get_state_message:109] (MainThread) SUCCESS MSG: No Event Creation
```
As i see in the code, cic try to call **configure_cpx_for_all_apps** function, get an exception, than try to execute **reinit_kubernetes**. It calls **stop_crd_thread** and get an exception during stopping watch on CRD. It happens every 15 seconds. 

How can i fix it?

**Comment by andy812** [comment]
We fixed the problem. Kubernetes services with LoadBalancer type breaks the CIC.

**Comment by RaveendraHolla** [comment]
Issue with targetRef is fixed in latest CIC version. Can you try and update.

CIC version 1.9.9: quay.io/citrix/citrix-k8s-ingress-controller:1.9.9
RBAC and CIC Yaml can be fetched from following path:
https://raw.githubusercontent.com/citrix/citrix-k8s-ingress-controller/master/deployment/baremetal/citrix-k8s-ingress-controller.yaml

**Comment by RaveendraHolla** [comment]
Issue with targetRef is fixed in latest CIC version. Can you try and update.

CIC version 1.9.9: quay.io/citrix/citrix-k8s-ingress-controller:1.9.9
RBAC and CIC Yaml can be fetched from following path:
https://raw.githubusercontent.com/citrix/citrix-k8s-ingress-controller/master/deployment/baremetal/citrix-k8s-ingress-controller.yaml

**Comment by ankits123** [comment]
Fix available in latest build.
